name: Build, Test, Deploy

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./scrum_poker
    - name: Build app
      run: dotnet build --configuration Release --no-restore
      working-directory: ./scrum_poker
    - name: Run all tests
      run: dotnet test
      working-directory: ./scrum_poker.Tests
    - name: Publish
      run: |
        dotnet publish -c Release -o scrum_poker
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v1
      with:
        app-name: scrum-poker1
        publish-profile: ${{ secrets.publish_profile }}
        package: './scrum_poker'
