name: DevBuildTest

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./scrum_poker
    - name: Build app
      run: dotnet build --configuration Release --no-restore
      working-directory: ./scrum_poker
    - name: Run SpecFlow tests
      run: dotnet test
      working-directory: ./scrum_poker.Tests
    - name: Run NUnit tests
      run: dotnet test
      working-directory: ./scrum_poker.Tests.NUnit
